### ISSUE TITLE
Set table border color for Plus Editor

### ISSUE THREAD

**Issue by timbeglinger** [standardnotes/titanium-theme#4]
When creating a table, you don't see the borders of the cells. They are having the same color as the background. Could we make them visible by adding:

```CSS
#plus-editor .table-bordered td {
  border-color: var(--note-cell-border-color);
}
```
